version: "3"

services:
  svelte:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}_PROJECT"
    restart: always
    command:
      "npm run start"


  nginx:
    image: nginx:1.13
    container_name: "${COMPOSE_PROJECT_NAME}_NGINX"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - svelte

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - ./:/var/www
    command: certonly --webroot --webroot-path=/var/www/html --email indexpro24@gmail.com --agree-tos --no-eff-email -d larux.ru

volumes:
  etc-letsencrypt:
